export const AppSettings = {
  // apps/franchisees/franchisee-list started
  apps_franchisee_franchiseeList_main_title_en: 'Franchisee',
  apps_franchisee_franchiseeList_search_placeholder_en: 'Search for',
  apps_franchisee_franchiseeList_create_btn_en: 'Add New',
  apps_franchisee_franchiseeList_viewAll_btn_en: 'View All',
  apps_franchisee_franchiseeList_cards_partners_en: 'PARTNERS',
  apps_franchisee_franchiseeList_cards_partner_en: 'PARTNER',
  // apps/franchisees/franchisee-list ended

  // apps/crm/create-franchisee started
  apps_crm_createFranchisee_main_title_en: 'Create New Franchisee',
  apps_crm_EditFranchisee_main_title_en: 'Edit Franchisee',
  apps_crm_createFranchisee_cancel_btn_en: 'Cancel',
  apps_crm_editFranchisee_save_franchisee_btn_en: 'Save Franchisee',
  apps_crm_editFranchisee_save_partner_btn_en: "Save Partner",
  apps_crm_createFranchisee_addPartner_btn_en: 'Add Partner',
  apps_crm_createFranchisee_sub_title_en: 'Franchisee Information',
  apps_crm_createFranchisee_sub_partner_info: 'Partner Information',
  apps_crm_createFranchisee_input_leadsource: 'Lead Source',
  apps_crm_createFranchisee_input_franchisee_name: 'Company Name',
  apps_crm_createFranchisee_input_placeholder_leadsource: 'Lead Source *',
  apps_crm_createFranchisee_input_investment: 'Investment',
  apps_crm_createFranchisee_input_placeholder_investment: 'Investment *',
  apps_crm_createFranchisee_input_franchiseeType: 'Franchisee Type',
  apps_crm_createFranchisee_input_modelType: 'Model Type',
  apps_crm_createFranchisee_input_placeholder_franchiseeType: 'Franchisee Type *',
  apps_crm_createFranchisee_input_howTostartSoon: 'How soon to start',
  apps_crm_createFranchisee_input_placeholder_howTostartSoon: 'How soon to start *',
  apps_crm_createFranchisee_input_Date: 'When do you want to start?',
  apps_crm_createFranchisee_input_Time: 'Time',
  apps_crm_createFranchisee_input_address: 'Address',
  apps_crm_createFranchisee_input_City: 'City',
  apps_crm_createFranchisee_input_State: 'State',
  apps_crm_createFranchisee_input_Country: 'Country',
  apps_crm_createFranchisee_input_FranchiseePincode: 'Pincode',
  apps_crm_createFranchisee_input_Remarks: 'Remarks',
  apps_crm_createFranchisee_input_Name: 'Full Name',
  apps_crm_createFranchisee_input_Email: 'Email',
  apps_crm_createFranchisee_input_Age: 'Age',
  apps_crm_createFranchisee_input_Number: 'Number',
  apps_crm_createFranchisee_input_Occupation: 'Occupation',
  apps_crm_createFranchisee_input_BusinessType: 'Business Type',
  apps_crm_createFranchisee_Create_btn_en: 'Create',
  apps_crm_createFranchisee_DisplayImage_en: 'Profile Picture',
  create_franchisee_email_validation_en: 'You must enter a email',
  create_franchisee_email_validation2_en: 'Not a valid email',
  create_franchisee_name_validation_en: 'You must enter your name',
  create_franchisee_city_validation_en: 'You must enter your location',
  create_franchisee_occupation_validation_en: 'You must enter your occupation',
  create_franchisee_state_validation_en: 'You must enter your state',
  create_franchisee_address_validation_en: 'You must enter your address',
  create_franchisee_mobile_validation_en: 'You must enter your number',
  create_franchisee_investment_validation_en: 'You must select a value',
  create_franchisee_date_validation_en: 'You must select a date',
  create_franchisee_time_validation_en: 'You must enter time',
  create_franchisee_toStart_validation_en: 'You must enter a value',
  create_franchisee_age_validation_en: 'You must enter your age',
  create_franchisee_source_validation_en: 'You must enter your source',
  // apps/crm/create-franchisee ended

};
